<template>
  <view class="tokens-page" :data-theme="theme">
    <wbbb-navbar title="状态规范" left-arrow left-text="首页" @click-left="goBack" />
    <view class="tokens-page__hero"><text>设计色板</text><text>亮色、深色与交互状态均来自同一组 Wbbb token。</text><wbbb-button size="small" plain type="primary" @click="theme = theme === 'light' ? 'dark' : 'light'">切换{{ theme === 'light' ? '深色' : '浅色' }}</wbbb-button></view>
    <view class="tokens-page__section"><text>语义色</text><view class="tokens-page__grid"><view v-for="item in semanticColors" :key="item.type" class="color-card"><view class="color-card__solid" :class="`color-card__solid--${item.type}`"><text>{{ item.name }}</text></view><view class="color-card__soft" :class="`color-card__soft--${item.type}`">浅色容器 / 边界 / 错误提示</view></view></view></view>
    <view class="tokens-page__section"><text>控件状态</text><wbbb-card><view class="tokens-page__buttons"><wbbb-button>默认</wbbb-button><wbbb-button type="primary">按压反馈</wbbb-button><wbbb-button type="success">成功</wbbb-button><wbbb-button type="warning">警告</wbbb-button><wbbb-button type="danger">危险</wbbb-button><wbbb-button type="info">信息</wbbb-button><wbbb-button disabled>禁用</wbbb-button><wbbb-button loading type="primary">加载</wbbb-button></view></wbbb-card></view>
  </view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const theme = ref<'light' | 'dark'>('light')
const semanticColors = [{ name: '主色', type: 'primary' }, { name: '成功', type: 'success' }, { name: '警告', type: 'warning' }, { name: '危险', type: 'danger' }, { name: '信息', type: 'info' }]
function goBack() { uni.navigateBack() }
</script>

<style lang="scss">
.tokens-page { background: var(--wbbb-color-bg); min-height: 100vh; padding-bottom: 52rpx; }.tokens-page__hero { background: var(--wbbb-color-surface); display: flex; flex-direction: column; gap: 16rpx; padding: 40rpx 32rpx; }.tokens-page__hero text:first-child, .tokens-page__section > text { color: var(--wbbb-color-text); display: block; font-size: 34rpx; font-weight: 700; }.tokens-page__hero text:nth-child(2) { color: var(--wbbb-color-text-secondary); font-size: 24rpx; line-height: 1.6; }.tokens-page__hero .wbbb-button { align-self: flex-start; }.tokens-page__section { padding: 32rpx 24rpx 0; }.tokens-page__section > text { font-size: 30rpx; margin-bottom: 16rpx; }.tokens-page__grid { display: grid; gap: 16rpx; grid-template-columns: repeat(2, minmax(0, 1fr)); }.color-card { background: var(--wbbb-color-surface); border: 1rpx solid var(--wbbb-color-separator); border-radius: var(--wbbb-radius-lg); overflow: hidden; }.color-card__solid { align-items: center; color: var(--wbbb-color-primary-foreground); display: flex; font-size: 26rpx; font-weight: 700; height: 104rpx; justify-content: center; }.color-card__soft { font-size: 20rpx; line-height: 1.45; padding: 16rpx; }.color-card__solid--primary { background: var(--wbbb-color-primary); color: var(--wbbb-color-primary-foreground); }.color-card__soft--primary { background: var(--wbbb-color-primary-soft); color: var(--wbbb-color-primary); }.color-card__solid--success { background: var(--wbbb-color-success); color: var(--wbbb-color-success-foreground); }.color-card__soft--success { background: var(--wbbb-color-success-soft); color: var(--wbbb-color-success); }.color-card__solid--warning { background: var(--wbbb-color-warning); color: var(--wbbb-color-warning-foreground); }.color-card__soft--warning { background: var(--wbbb-color-warning-soft); color: var(--wbbb-color-warning); }.color-card__solid--danger { background: var(--wbbb-color-danger); color: var(--wbbb-color-danger-foreground); }.color-card__soft--danger { background: var(--wbbb-color-danger-soft); color: var(--wbbb-color-danger); }.color-card__solid--info { background: var(--wbbb-color-info); color: var(--wbbb-color-info-foreground); }.color-card__soft--info { background: var(--wbbb-color-info-soft); color: var(--wbbb-color-info); }.tokens-page__section .wbbb-card { padding: 24rpx; }.tokens-page__buttons { display: flex; flex-wrap: wrap; gap: 16rpx; }
</style>
