import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import subsetFont from 'subset-font'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const packageRoot = join(root, 'packages', 'wbbb-ui')
const sourceRoot = join(packageRoot, 'src', 'icons')
const lucideRoot = join(root, 'node_modules', '@react-native-vector-icons', 'lucide')
const glyphmap = JSON.parse(readFileSync(join(lucideRoot, 'glyphmaps', 'Lucide.json'), 'utf8'))
const sourceFont = readFileSync(join(lucideRoot, 'fonts', 'Lucide.ttf'))

export const coreIcons = [
  'arrow-left', 'arrow-right', 'arrow-up', 'arrow-down', 'chevron-left', 'chevron-right', 'chevron-up', 'chevron-down', 'menu', 'more-horizontal',
  'plus', 'minus', 'x', 'check', 'search', 'pencil', 'trash-2', 'copy', 'refresh-cw', 'external-link',
  'circle-check', 'circle-x', 'circle-alert', 'triangle-alert', 'info', 'circle-help', 'loader-circle',
  'user', 'users', 'user-plus', 'bell', 'mail', 'phone', 'message-circle',
  'image', 'camera', 'upload', 'download', 'file', 'file-text', 'folder', 'paperclip', 'play', 'pause',
  'calendar', 'clock', 'map-pin', 'map', 'filter', 'sliders-horizontal', 'settings', 'lock', 'eye', 'eye-off',
  'home', 'heart', 'star', 'shopping-cart', 'credit-card', 'package', 'grid-2x2', 'list', 'bar-chart-3', 'trending-up'
]

const aliases = {
  back: 'chevron-left',
  close: 'x',
  default: 'circle-help',
  down: 'chevron-down',
  error: 'circle-x',
  left: 'chevron-left',
  right: 'chevron-right',
  success: 'circle-check',
  up: 'chevron-up',
  warning: 'triangle-alert'
}

mkdirSync(sourceRoot, { recursive: true })

const missing = coreIcons.filter((name) => glyphmap[name] === undefined)
if (missing.length > 0) {
  throw new Error(`Lucide font is missing core icons: ${missing.join(', ')}`)
}

const codepoints = Object.fromEntries(coreIcons.map((name) => [name, glyphmap[name]]))
const glyphText = coreIcons.map((name) => String.fromCodePoint(codepoints[name])).join('')
const ttf = await subsetFont(sourceFont, glyphText, { targetFormat: 'sfnt' })
const woff = await subsetFont(sourceFont, glyphText, { targetFormat: 'woff' })
if (!ttf.byteLength || !woff.byteLength || Object.keys(codepoints).length !== coreIcons.length) {
  throw new Error('Core icon font generation did not create the expected assets.')
}

writeFileSync(join(sourceRoot, 'wbbb-icons.ttf'), ttf)
writeFileSync(join(sourceRoot, 'wbbb-icons.woff'), woff)
writeFileSync(join(sourceRoot, 'manifest.ts'), `// Generated by scripts/generate-icons.mjs. Do not edit manually.\nexport const wbbbCoreIcons = ${JSON.stringify(coreIcons, null, 2)} as const\n\nexport const wbbbCoreIconCodepoints = ${JSON.stringify(codepoints, null, 2)} as const\n\nexport const wbbbIconAliases = ${JSON.stringify(aliases, null, 2)} as const\n\nexport type WbbbCoreIconName = (typeof wbbbCoreIcons)[number]\n`)

console.log(`Generated ${coreIcons.length} Wbbb core icons.`)
